(()=>{
const K='ghestban_family_lock_v1', S='ghestban_manager_until';
const mobile=()=>document.body.classList.add('gh-mobile');
const unlocked=()=>Number(sessionStorage.getItem(S)||0)>Date.now();
const hash=async s=>{const b=new TextEncoder().encode(s);const d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const cfg=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}};
async function setPin(){const a=prompt('یک PIN حداقل ۴ رقمی برای مدیریت وارد کنید:');if(!a)return;if(!/^\d{4,}$/.test(a)){alert('PIN باید حداقل ۴ رقم باشد.');return}const b=prompt('PIN را دوباره وارد کنید:');if(a!==b){alert('PINها یکسان نیستند.');return}localStorage.setItem(K,JSON.stringify({enabled:true,pinHash:await hash(a)}));sessionStorage.removeItem(S);renderBanner();alert('حالت مشاهده خانوادگی فعال شد.')}
async function unlock(){const c=cfg();if(!c?.enabled){await setPin();return unlocked()}return new Promise(resolve=>{const o=document.createElement('div');o.className='gh-lock';o.innerHTML='<div class="gh-lock-card"><h3>ورود به حالت مدیریت</h3><div>برای تغییر اطلاعات PIN مدیر را وارد کنید.</div><input inputmode="numeric" type="password" maxlength="12" autofocus><div class="gh-lock-actions"><button data-x>انصراف</button><button class="primary" data-ok>باز کردن</button></div></div>';document.body.appendChild(o);const i=o.querySelector('input');const done=v=>{o.remove();resolve(v)};o.querySelector('[data-x]').onclick=()=>done(false);o.querySelector('[data-ok]').onclick=async()=>{if(await hash(i.value)===c.pinHash){sessionStorage.setItem(S,String(Date.now()+5*60*1000));renderBanner();done(true)}else alert('PIN نادرست است.')};i.onkeydown=e=>{if(e.key==='Enter')o.querySelector('[data-ok]').click()};i.focus()})}
function renderBanner(){document.querySelector('.gh-view-banner')?.remove();const c=cfg();if(!c?.enabled)return;const b=document.createElement('div');b.className='gh-view-banner';b.innerHTML=unlocked()?'<span>🔓 حالت مدیریت — قفل خودکار پس از ۵ دقیقه</span><button class="small">قفل</button>':'<span>👁 حالت مشاهده خانوادگی</span><button class="small">ورود مدیر</button>';b.querySelector('button').onclick=()=>{if(unlocked()){sessionStorage.removeItem(S);renderBanner()}else unlock()};document.querySelector('.wrap')?.prepend(b)}
function nav(){const n=document.createElement('nav');n.className='gh-bottom-nav';n.innerHTML='<button data-go="top"><span class="ico">⌂</span>خانه</button><button data-find="قسط"><span class="ico">▤</span>اقساط</button><button data-add class="add" aria-label="افزودن">＋</button><button data-find="گزارش"><span class="ico">▥</span>گزارش‌ها</button><button data-more><span class="ico">☰</span>بیشتر</button>';document.body.appendChild(n);n.querySelector('[data-go]').onclick=()=>scrollTo({top:0,behavior:'smooth'});n.querySelectorAll('[data-find]').forEach(b=>b.onclick=()=>{const q=b.dataset.find;const el=[...document.querySelectorAll('h2,.tab,button')].find(x=>x.textContent.includes(q));el?.scrollIntoView({behavior:'smooth',block:'start'})});n.querySelector('[data-add]').onclick=async()=>{if(cfg()?.enabled&&!unlocked()&&!(await unlock()))return;const el=[...document.querySelectorAll('button')].find(x=>/افزودن|ثبت.*جدید|وام جدید/.test(x.textContent));el?.click()};n.querySelector('[data-more]').onclick=()=>{const el=document.querySelector('header .actions');el?.scrollIntoView({behavior:'smooth',block:'center'})}}
function guard(){document.addEventListener('click',async e=>{const c=cfg();if(!c?.enabled||unlocked())return;const b=e.target.closest('button');if(!b||b.closest('.gh-bottom-nav')||b.closest('.gh-view-banner')||b.closest('.gh-lock'))return;const t=(b.textContent||'').trim();if(/ویرایش|حذف|پرداخت|افزودن|ثبت|ذخیره|بازیابی|Pull|Push|همگام|تنظیم/.test(t)){e.preventDefault();e.stopImmediatePropagation();if(await unlock())b.click()}},true)}
document.addEventListener('DOMContentLoaded',()=>{mobile();nav();renderBanner();guard();if(!cfg())setTimeout(()=>{if(confirm('حالت مشاهده خانوادگی فعال شود؟ تغییرات فقط با PIN مدیر انجام خواهد شد.'))setPin()},700)});
window.GhestbanFamily={setPin,unlock,lock:()=>{sessionStorage.removeItem(S);renderBanner()}};
})();