(()=>{
const K='ghestban_family_lock_v1',S='ghestban_manager_until';
const cfg=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}};
const unlocked=()=>Number(sessionStorage.getItem(S)||0)>Date.now();
const hash=async s=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')};
function closeSheet(){document.querySelector('.gh-sheet')?.remove()}
function sheet(title,html){closeSheet();const o=document.createElement('div');o.className='gh-sheet';o.innerHTML='<div class="gh-sheet-card"><div class="gh-handle"></div><h3>'+title+'</h3>'+html+'</div>';o.onclick=e=>{if(e.target===o)closeSheet()};document.body.appendChild(o);return o}
async function setPin(){const a=prompt('PIN مدیر (حداقل ۴ رقم):');if(!a)return false;if(!/^\d{4,}$/.test(a)){alert('PIN باید حداقل ۴ رقم باشد.');return false}const b=prompt('PIN را دوباره وارد کنید:');if(a!==b){alert('PINها یکسان نیستند.');return false}localStorage.setItem(K,JSON.stringify({enabled:true,pinHash:await hash(a)}));sessionStorage.removeItem(S);renderBanner();return true}
async function unlock(){const c=cfg();if(!c?.enabled){if(!(await setPin()))return false}const cc=cfg();return new Promise(resolve=>{const o=document.createElement('div');o.className='gh-lock';o.innerHTML='<div class="gh-lock-card"><h3>🔐 ورود به حالت مدیریت</h3><div>برای تغییر اطلاعات PIN مدیر را وارد کنید.</div><input inputmode="numeric" type="password" maxlength="12" autocomplete="off"><div class="gh-lock-actions"><button data-x>انصراف</button><button class="primary" data-ok>ورود</button></div></div>';document.body.appendChild(o);const i=o.querySelector('input'),done=v=>{o.remove();resolve(v)};o.querySelector('[data-x]').onclick=()=>done(false);o.querySelector('[data-ok]').onclick=async()=>{if(await hash(i.value)===cc.pinHash){sessionStorage.setItem(S,String(Date.now()+5*60*1000));renderBanner();done(true)}else alert('PIN نادرست است.')};i.onkeydown=e=>e.key==='Enter'&&o.querySelector('[data-ok]').click();i.focus()})}
function renderBanner(){document.querySelector('.gh-view-banner')?.remove();if(!cfg()?.enabled)return;const b=document.createElement('div');b.className='gh-view-banner';b.innerHTML=unlocked()?'<span>🔓 حالت مدیریت</span><button class="small">قفل مدیریت</button>':'<span>👁 حالت مشاهده خانوادگی</span><button class="small">ورود مدیر</button>';b.querySelector('button').onclick=async()=>{if(unlocked()){sessionStorage.removeItem(S);renderBanner()}else await unlock()};document.querySelector('.wrap')?.prepend(b)}
const findClick=(rx)=>{const e=[...document.querySelectorAll('button,.tab,.page-tab')].find(x=>rx.test((x.textContent||'').trim()));if(e){e.click();e.scrollIntoView({behavior:'smooth',block:'center'})}return!!e};
function syncSheet(){const o=sheet('پشتیبان‌گیری و همگام‌سازی','<div class="gh-sync-choice"><button data-file>📥 ورود / خروج فایل<small>بدون نیاز به GitHub؛ مناسب انتقال بین اعضای خانواده</small></button><button data-gh>◉ GitHub (پیشرفته)<small>برای پشتیبان نسخه‌بندی‌شده و همگام‌سازی کاربران حرفه‌ای</small></button></div>');o.querySelector('[data-file]').onclick=()=>{closeSheet();findClick(/پشتیبان|بازیابی|درون.?ریزی|برون.?ریزی|Import|Export/i)};o.querySelector('[data-gh]').onclick=()=>{closeSheet();findClick(/GitHub|گیت.?هاب|همگام/i)}}
function more(){const o=sheet('بیشتر','<div class="gh-menu-card"><b>حالت خانواده</b><span>'+(cfg()?.enabled?(unlocked()?'مدیریت باز است':'فقط مشاهده'):'فعال نشده')+'</span></div><button class="gh-menu-item" data-family><span class="mi">👥</span>خانواده و دسترسی<span class="chev">‹</span></button><button class="gh-menu-item" data-rem><span class="mi">🔔</span>یادآورها و اعلان‌ها<span class="chev">‹</span></button><button class="gh-menu-item" data-sync><span class="mi">☁️</span>پشتیبان‌گیری و همگام‌سازی<span class="chev">‹</span></button><button class="gh-menu-item" data-set><span class="mi">⚙️</span>تنظیمات<span class="chev">‹</span></button><button class="gh-menu-item" data-about><span class="mi">ⓘ</span>درباره قسطبان<span class="chev">‹</span></button>');o.querySelector('[data-family]').onclick=async()=>{closeSheet();cfg()?.enabled?await unlock():await setPin()};o.querySelector('[data-rem]').onclick=()=>{closeSheet();findClick(/یادآور|اعلان/i)};o.querySelector('[data-sync]').onclick=()=>syncSheet();o.querySelector('[data-set]').onclick=()=>{closeSheet();findClick(/تنظیمات/i)};o.querySelector('[data-about]').onclick=()=>{closeSheet();findClick(/درباره/i)}}
function nav(){const n=document.createElement('nav');n.className='gh-bottom-nav';n.innerHTML='<button class="active" data-home><span class="ico">⌂</span>خانه</button><button data-inst><span class="ico">▤</span>اقساط</button><button data-add class="add" aria-label="افزودن">＋</button><button data-report><span class="ico">▥</span>گزارش‌ها</button><button data-more><span class="ico">☰</span>بیشتر</button>';document.body.appendChild(n);const active=b=>{n.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b?.classList.add('active')};n.querySelector('[data-home]').onclick=e=>{active(e.currentTarget);scrollTo({top:0,behavior:'smooth'});findClick(/داشبورد|خانه/i)};n.querySelector('[data-inst]').onclick=e=>{active(e.currentTarget);findClick(/اقساط|وام|طرح/i)};n.querySelector('[data-report]').onclick=e=>{active(e.currentTarget);findClick(/گزارش/i)};n.querySelector('[data-more]').onclick=e=>{active(e.currentTarget);more()};n.querySelector('[data-add]').onclick=async()=>{if(cfg()?.enabled&&!unlocked()&&!(await unlock()))return;findClick(/افزودن|ثبت.*جدید|وام جدید|طرح جدید/i)}}
function guard(){document.addEventListener('click',async e=>{if(!cfg()?.enabled||unlocked())return;const b=e.target.closest('button');if(!b||b.closest('.gh-bottom-nav,.gh-view-banner,.gh-lock,.gh-sheet'))return;const t=(b.textContent||'').trim();if(/ویرایش|حذف|پرداخت|افزودن|ثبت|ذخیره|بازیابی|Pull|Push|همگام|تنظیم/i.test(t)){e.preventDefault();e.stopImmediatePropagation();if(await unlock())b.click()}},true)}
function enhanceHome(){const wrap=document.querySelector('.wrap');if(!wrap)return;const hero=document.createElement('section');hero.className='gh-mobile-hero';hero.innerHTML='<div><small>خلاصه وضعیت</small><h2>مدیریت اقساط</h2><p>سررسیدها و پرداخت‌های خود را یکجا ببینید.</p></div><button data-quick>＋ قسط جدید</button>';const h=wrap.querySelector('header');(h?.nextSibling?h.parentNode.insertBefore(hero,h.nextSibling):wrap.prepend(hero));hero.querySelector('[data-quick]').onclick=async()=>{if(cfg()?.enabled&&!unlocked()&&!(await unlock()))return;findClick(/افزودن|ثبت.*جدید|وام جدید|طرح جدید/i)};document.querySelectorAll('.stats .stat').forEach((x,i)=>{x.classList.add('gh-stat-card');x.dataset.order=i+1})}
document.addEventListener('DOMContentLoaded',()=>{document.body.classList.add('gh-mobile');enhanceHome();nav();renderBanner();guard()});
window.GhestbanMobile={more,syncSheet,setPin,unlock,lock:()=>{sessionStorage.removeItem(S);renderBanner()}};
})();