(()=>{
const P=()=>window.GhestbanPlatform;
function close(){document.querySelector('.gh-page')?.remove()}
function page(title,html){close();const d=document.createElement('section');d.className='gh-page';d.innerHTML='<header><button data-close>→</button><h2>'+title+'</h2></header><main>'+html+'</main>';document.body.appendChild(d);d.querySelector('[data-close]').onclick=close;return d}
const money=n=>(Number(n)||0).toLocaleString('fa-IR')+' تومان';
function transactions(){const tx=P().transactions(),pending=P().inbox().filter(x=>x.status==='pending');const d=page('تراکنش‌ها','<div class="gh-seg"><button class="active" data-all>همه تراکنش‌ها</button><button data-pending>منتظر تأیید <b>'+pending.length+'</b></button></div><div data-body></div>');const body=d.querySelector('[data-body]');const all=()=>{body.innerHTML='<button class="gh-primary-wide" data-new>＋ ثبت تراکنش</button>'+(tx.length?tx.map(t=>'<article class="gh-list-card"><b>'+(t.kind==='income'?'درآمد':t.kind==='transfer'?'انتقال':'هزینه')+'</b><strong>'+money(t.amount)+'</strong><small>'+(t.category||t.note||'بدون دسته‌بندی')+'</small></article>').join(''):'<div class="gh-empty">هنوز تراکنشی ثبت نشده است.</div>');body.querySelector('[data-new]')?.addEventListener('click',quickTransaction)};const pend=()=>{body.innerHTML=pending.length?pending.map(c=>'<article class="gh-list-card gh-candidate" data-id="'+c.id+'"><b>'+(c.direction==='income'?'واریز شناسایی‌شده':'برداشت شناسایی‌شده')+'</b><strong>'+money(c.amount)+'</strong><small>'+(c.source==='bank-shahr-sms'?'پیامک بانک شهر':'ورودی محلی')+'</small><div><button data-kind="expense">هزینه</button><button data-kind="income">درآمد</button><button data-kind="transfer">انتقال</button><button data-ignore>نادیده گرفتن</button></div></article>').join(''):'<div class="gh-empty">تراکنش منتظر تأیید ندارید.</div>';body.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{P().resolveCandidate(b.closest('[data-id]').dataset.id,b.dataset.kind);transactions()});body.querySelectorAll('[data-ignore]').forEach(b=>b.onclick=()=>{P().ignoreCandidate(b.closest('[data-id]').dataset.id);transactions()})};d.querySelector('[data-all]').onclick=e=>{d.querySelectorAll('.gh-seg button').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');all()};d.querySelector('[data-pending]').onclick=e=>{d.querySelectorAll('.gh-seg button').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');pend()};all()}
function quickTransaction(){const amount=prompt('مبلغ تراکنش به تومان:');if(!amount)return;const kind=prompt('نوع: expense / income / transfer','expense')||'expense';const note=prompt('شرح / دسته‌بندی (اختیاری):')||'';P().addTransaction({amount:String(amount).replace(/\D/g,''),kind,note});transactions()}
function accounts(){const a=P().accounts(),h=P().family();const d=page('حساب‌ها و کارت‌ها','<button class="gh-primary-wide" data-add>＋ افزودن حساب / کارت</button>'+(a.length?a.map(x=>'<article class="gh-list-card"><b>'+x.bank+' — '+(x.label||'کارت/حساب')+'</b><strong>'+(x.number?'•••• '+x.number.replace(/\D/g,'').slice(-4):'بدون شماره')+'</strong><small>مالک: '+(h.members.find(m=>m.id===x.ownerId)?.name||'مدیر')+(x.smsMonitor?' · پایش پیامک':'')+'</small></article>').join(''):'<div class="gh-empty">هنوز حساب یا کارتی تعریف نشده است.</div>');d.querySelector('[data-add]').onclick=()=>{const bank=prompt('نام بانک:','بانک شهر');if(!bank)return;const number=prompt('شماره کارت / حساب:')||'';const label=prompt('عنوان:','کارت پرداخت')||'';P().addAccount({bank,number,label,smsMonitor:/شهر/.test(bank)});accounts()}}
function family(){const h=P().family();const d=page('اعضای خانواده','<button class="gh-primary-wide" data-add>＋ افزودن عضو</button>'+h.members.map(m=>'<article class="gh-list-card"><b>'+m.name+'</b><strong>'+(m.role==='owner'?'مدیر':m.role==='contributor'?'ثبت‌کننده':'مشاهده‌گر')+'</strong><small>'+(m.contact||'حساب محلی')+'</small></article>').join('')+'<div class="gh-info">دعوت آنلاین، OTP و دستگاه‌ها بعد از فعال شدن Server Mode/VPS به همین مدل متصل می‌شوند.</div>');d.querySelector('[data-add]').onclick=()=>{const name=prompt('نام عضو خانواده:');if(!name)return;const contact=prompt('شماره موبایل (اختیاری):')||'';const role=prompt('سطح دسترسی: contributor یا viewer','viewer')==='contributor'?'contributor':'viewer';P().addMember({name,contact,role});family()}}
function notifications(){const n=P().notifications();page('اعلان‌ها',n.length?n.map(x=>'<article class="gh-list-card"><b>'+x.title+'</b><span>'+x.body+'</span><small>'+new Date(x.at).toLocaleString('fa-IR')+'</small></article>').join(''):'<div class="gh-empty">اعلان جدیدی ندارید.</div>')}
function reports(){const tx=P().transactions(),income=tx.filter(x=>x.kind==='income').reduce((s,x)=>s+x.amount,0),expense=tx.filter(x=>x.kind==='expense').reduce((s,x)=>s+x.amount,0);page('گزارش‌ها','<div class="gh-report-grid"><article><small>درآمد ثبت‌شده</small><b>'+money(income)+'</b></article><article><small>هزینه ثبت‌شده</small><b>'+money(expense)+'</b></article><article><small>خالص تراکنش‌ها</small><b>'+money(income-expense)+'</b></article><article><small>تراکنش منتظر تأیید</small><b>'+P().inbox().filter(x=>x.status==='pending').length+'</b></article></div><div class="gh-info">گزارش‌های هسته اقساط در نسخه اصلی حفظ شده‌اند؛ این صفحه لایه گزارش تراکنش و خانواده را اضافه می‌کند.</div>')}
function more(){const d=page('بیشتر','<button class="gh-settings-row" data-r>گزارش‌ها <i>‹</i></button><button class="gh-settings-row" data-a>حساب‌ها و کارت‌ها <i>‹</i></button><button class="gh-settings-row" data-f>اعضای خانواده <i>‹</i></button><button class="gh-settings-row" data-n>اعلان‌ها <i>‹</i></button><button class="gh-settings-row" data-b>پشتیبان و همگام‌سازی <i>‹</i></button><button class="gh-settings-row" data-s>تنظیمات <i>‹</i></button><button class="gh-settings-row" data-about>درباره قسطبان <i>‹</i></button>');d.querySelector('[data-r]').onclick=reports;d.querySelector('[data-a]').onclick=accounts;d.querySelector('[data-f]').onclick=family;d.querySelector('[data-n]').onclick=notifications;d.querySelector('[data-b]').onclick=()=>{close();window.GhestbanMobile?.syncSheet()};d.querySelector('[data-s]').onclick=()=>{close();window.GhestbanSettings?.open()};d.querySelector('[data-about]').onclick=()=>alert('قسطبان 3.11.0-beta.1\nمدیریت هوشمند اقساط و امور مالی خانواده\nمحصولی از خدمات کامپیوتر الماس')}
function addMenu(){const o=window.GhestbanMobile?.sheet?.('ثبت جدید','<div class="gh-sync-choice"><button data-loan>🧾 ثبت وام / قسط<small>Wizard برنامه اقساط</small></button><button data-exp>💳 ثبت هزینه<small>خرید و پرداخت روزمره</small></button><button data-inc>💰 ثبت درآمد<small>واریز و درآمد</small></button><button data-tr>⇄ انتقال بین حساب‌ها<small>در گزارش هزینه/درآمد خنثی است</small></button></div>');if(!o)return window.GhestbanWizard?.open();o.querySelector('[data-loan]').onclick=()=>{o.remove();window.GhestbanWizard?.open()};[['exp','expense'],['inc','income'],['tr','transfer']].forEach(([k,v])=>o.querySelector('[data-'+k+']').onclick=()=>{o.remove();const amount=prompt('مبلغ به تومان:');if(amount)P().addTransaction({amount:String(amount).replace(/\D/g,''),kind:v,note:prompt('شرح (اختیاری):')||''})})}
window.GhestbanPages={close,transactions,accounts,family,notifications,reports,more,addMenu};
})();