(()=>{
const DRAFT='ghestban_loan_wizard_draft_v1';
const $=id=>document.getElementById(id), en=s=>String(s||'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const val=id=>$(id)?.value?.trim()||'', set=(id,v)=>{if($(id))$(id).value=v??''}, yes=n=>document.querySelector('input[name="'+n+'"]:checked')?.value==='yes';
function saveDraft(){const o={cat:val('gwCat'),person:val('gwPerson'),principal:val('gwPrincipal'),amount:val('gwAmount'),total:val('gwTotal'),paid:val('gwPaid'),due:val('gwDue'),cycle:val('gwCycle'),rate:val('gwRate'),dest:val('gwDest'),payCard:val('gwPayCard'),auto:yes('gwAuto'),autoAccount:val('gwAutoAccount'),link:val('gwLink'),notes:val('gwNotes'),step:Number(document.querySelector('.gh-wizard')?.dataset.step||1)};localStorage.setItem(DRAFT,JSON.stringify(o))}
function loadDraft(){try{return JSON.parse(localStorage.getItem(DRAFT)||'null')}catch{return null}}
function renderStep(w,n){w.dataset.step=n;w.querySelectorAll('.gw-step').forEach(x=>x.hidden=Number(x.dataset.step)!==n);w.querySelector('[data-prev]').hidden=n===1;w.querySelector('[data-next]').hidden=n===5;w.querySelector('[data-save]').hidden=n!==5;w.querySelector('.gw-progress b').style.width=(n*20)+'%';w.querySelector('.gw-count').textContent='مرحله '+n+' از ۵';if(n===5)review(w)}
function req(n){if(n===1&&!val('gwCat'))return 'عنوان / بانک را وارد کنید.';if(n===2){if(!Number(en(val('gwAmount')).replace(/\D/g,'')))return 'مبلغ هر قسط را وارد کنید.';if(!Number(en(val('gwTotal')).replace(/\D/g,'')))return 'تعداد اقساط را وارد کنید.';if(!val('gwDue'))return 'تاریخ اولین/بعدی سررسید را وارد کنید.'}return''}
function review(w){w.querySelector('.gw-review').innerHTML='<b>'+val('gwCat')+'</b><span>مربوط به: '+(val('gwPerson')||'—')+'</span><span>'+val('gwTotal')+' قسط × '+val('gwAmount')+' ریال</span><span>سررسید: '+val('gwDue')+' · دوره '+(val('gwCycle')||'۱')+' ماه</span><span>نرخ سود: '+(val('gwRate')||'ثبت نشده')+(val('gwRate')?'٪':'')+'</span><span>مقصد قسط: '+(val('gwDest')||'ندارد')+'</span><span>کارت پرداخت: '+(val('gwPayCard')||'ندارد')+'</span><span>برداشت خودکار: '+(yes('gwAuto')?'بله':'خیر')+'</span>'}
function choice(name,label,target){return '<div class="gw-question"><b>'+label+'</b><label><input type="radio" name="'+name+'" value="no" checked> خیر</label><label><input type="radio" name="'+name+'" value="yes"> بله</label></div><div class="gw-conditional" data-for="'+name+'" hidden>'+target+'</div>'}
function open(){document.querySelector('.gh-wizard')?.remove();const d=loadDraft(),w=document.createElement('div');w.className='gh-wizard';w.innerHTML='<div class="gw-card"><header><button data-close>×</button><div><b>ثبت قسط جدید</b><small class="gw-count"></small></div></header><div class="gw-progress"><b></b></div><main>'+
'<section class="gw-step" data-step="1"><h2>مشخصات وام</h2><label>عنوان / بانک / صندوق *</label><input id="gwCat" placeholder="مثلاً بانک مسکن"><label>مربوط به</label><input id="gwPerson" placeholder="مثلاً فرهاد"><label>مبلغ اصل وام (اختیاری)</label><input id="gwPrincipal" inputmode="numeric" placeholder="ریال"></section>'+
'<section class="gw-step" data-step="2"><h2>برنامه اقساط</h2><label>مبلغ هر قسط *</label><input id="gwAmount" inputmode="numeric"><label>تعداد کل اقساط *</label><input id="gwTotal" inputmode="numeric"><label>تعداد پرداخت‌شده</label><input id="gwPaid" inputmode="numeric" value="۰"><label>اولین / سررسید بعدی *</label><input id="gwDue" placeholder="۱۴۰۵/۰۷/۲۷"><label>دوره پرداخت</label><select id="gwCycle"><option value="1">ماهانه</option><option value="2">هر دو ماه</option><option value="3">سه‌ماهه</option><option value="6">شش‌ماهه</option><option value="12">سالانه</option></select><label>نرخ سود سالانه (اختیاری)</label><input id="gwRate" inputmode="decimal" placeholder="مثلاً ۲۳"></section>'+
'<section class="gw-step" data-step="3"><h2>کارت‌ها و حساب‌ها</h2>'+choice('gwHasDest','آیا این قسط کارت/حساب مقصد دارد؟','<label>کارت / حساب / شبا مقصد قسط</label><input id="gwDest" inputmode="text" placeholder="شماره مقصد">')+choice('gwHasPay','آیا برای پرداخت قسط کارت مشخصی دارید؟','<label>کارت پرداخت</label><input id="gwPayCard" inputmode="numeric" placeholder="شماره کارت پرداخت">')+'</section>'+
'<section class="gw-step" data-step="4"><h2>پرداخت و امکانات اختیاری</h2>'+choice('gwAuto','آیا بانک قسط را خودکار برداشت می‌کند؟','<label>کارت / حساب برداشت خودکار</label><input id="gwAutoAccount" placeholder="شماره کارت یا حساب">')+'<label>لینک پرداخت بانک (اختیاری)</label><input id="gwLink" type="url" placeholder="https://..."><label>یادداشت (اختیاری)</label><textarea id="gwNotes"></textarea><p class="gw-skip">این مرحله کاملاً اختیاری است.</p></section>'+
'<section class="gw-step" data-step="5"><h2>مرور و ثبت</h2><div class="gw-review"></div><p>پس از ثبت، برنامه اقساط از اطلاعات بالا ساخته می‌شود و ویرایش پیشرفته همچنان در دسترس است.</p></section></main><footer><button data-prev>قبلی</button><button class="primary" data-next>ادامه</button><button class="primary" data-save>ثبت قسط</button></footer></div>';document.body.appendChild(w);
w.querySelectorAll('input[name]').forEach(r=>r.onchange=()=>{const box=w.querySelector('[data-for="'+r.name+'"]');if(box)box.hidden=!yes(r.name);saveDraft()});
if(d){for(const [k,v] of Object.entries({gwCat:d.cat,gwPerson:d.person,gwPrincipal:d.principal,gwAmount:d.amount,gwTotal:d.total,gwPaid:d.paid,gwDue:d.due,gwCycle:d.cycle,gwRate:d.rate,gwDest:d.dest,gwPayCard:d.payCard,gwAutoAccount:d.autoAccount,gwLink:d.link,gwNotes:d.notes}))set(k,v);if(d.dest){w.querySelector('input[name=gwHasDest][value=yes]').checked=true;w.querySelector('[data-for=gwHasDest]').hidden=false}if(d.payCard){w.querySelector('input[name=gwHasPay][value=yes]').checked=true;w.querySelector('[data-for=gwHasPay]').hidden=false}if(d.auto){w.querySelector('input[name=gwAuto][value=yes]').checked=true;w.querySelector('[data-for=gwAuto]').hidden=false}}
w.oninput=saveDraft;w.querySelector('[data-close]').onclick=()=>{saveDraft();w.remove()};w.querySelector('[data-prev]').onclick=()=>renderStep(w,Math.max(1,Number(w.dataset.step)-1));w.querySelector('[data-next]').onclick=()=>{const n=Number(w.dataset.step),e=req(n);if(e)return alert(e);saveDraft();renderStep(w,n+1)};
w.querySelector('[data-save]').onclick=()=>{const e=req(1)||req(2);if(e)return alert(e);const click=(rx)=>[...document.querySelectorAll('button')].find(x=>!x.closest('.gh-wizard,.gh-bottom-nav')&&rx.test((x.textContent||'').trim()))?.click();click(/قسط جدید|افزودن.*قسط|افزودن.*وام/);setTimeout(()=>{set('fCat',val('gwCat'));set('fPerson',val('gwPerson'));set('fAmount',val('gwAmount'));set('fTotal',val('gwTotal'));set('fPaid',val('gwPaid'));set('fDueDate',val('gwDue'));set('fCycle',val('gwCycle'));set('fRate',val('gwRate'));set('fPayLink',val('gwLink'));set('fNotes',val('gwNotes'));set('fAutoDebitCard',yes('gwAuto')?val('gwAutoAccount'):val('gwDest'));if($('fAutoDebit'))$('fAutoDebit').checked=yes('gwAuto');if(val('gwPrincipal')||val('gwDest')||val('gwPayCard')){const extra=[];if(val('gwPrincipal'))extra.push('اصل وام: '+val('gwPrincipal')+' ریال');if(val('gwDest'))extra.push('مقصد قسط: '+val('gwDest'));if(val('gwPayCard'))extra.push('کارت پرداخت: '+val('gwPayCard'));set('fNotes',[val('gwNotes'),...extra].filter(Boolean).join(' | '))}const gen=$('btnGenerateSchedule');if(gen)gen.click();const save=$('btnSaveLoan');if(save){save.click();localStorage.removeItem(DRAFT);w.remove()}},100)};
renderStep(w,d?.step||1)}
window.GhestbanWizard={open};
})();